# Generated by Django 4.0 on 2021-12-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_sudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('surface', models.IntegerField(verbose_name=5)),
                ('price', models.FloatField()),
                ('charges', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('send', models.BooleanField(default=False)),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.home')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.tenant')),
            ],
        ),
    ]
