# Generated by Django 4.0 on 2021-12-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_home_surface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='user_id',
            new_name='tenant_id',
        ),
        migrations.AddField(
            model_name='tenant',
            name='home_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='dashboard.home'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
