# Generated by Django 4.0 on 2021-12-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_user_id_receipt_tenant_id_tenant_home_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
