# Generated by Django 4.0 on 2021-12-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_home_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
